merchant_spending_type = {
    "Veterinary Services": "essential",
    "Agricultural Co-operatives": "essential",
    "Horticultural Services": "semi-essential",
    "Landscaping Services": "semi-essential",
    "General Contractors-Residential and Commercial": "semi-essential",
    "Air Conditioning Contractors – Sales and Installation": "semi-essential",
    "Heating Contractors – Sales, Service, Installation": "semi-essential",
    "Electrical Contractors": "semi-essential",
    "Insulation - Contractors": "semi-essential",
    "Masonry, Stonework Contractors": "semi-essential",
    "Plastering Contractors": "semi-essential",
    "Stonework and Masonry Contractors": "semi-essential",
    "Tile Settings Contractors": "semi-essential",
    "Carpentry Contractors": "semi-essential",
    "Roofing - Contractors": "semi-essential",
    "Sheet Metal Work - Contractors": "semi-essential",
    "Siding - Contractors": "semi-essential",
    "Contractors - Concrete Work": "semi-essential",
    "Contractors – Special Trade, Not Elsewhere Classified": "semi-essential",
    "Miscellaneous Publishing and Printing": "discretionary",
    "Typesetting, Plate Making, & Related Services": "discretionary",
    "Specialty Cleaning, Polishing, and Sanitation Preparations": "semi-essential",
    "UNITED AIRLINES": "semi-essential",
    "AMERICAN AIRLINES": "semi-essential",
    "PAN AMERICAN": "semi-essential",
    "TRANS WORLD AIRLINES": "semi-essential",
    "BRITISH AIRWAYS": "semi-essential",
    "JAPAN AIRLINES": "semi-essential",
    "AIR FRANCE": "semi-essential",
    "LUFTHANSA": "semi-essential",
    "AIR CANADA": "semi-essential",
    "KLM (ROYAL DUTCH AIRLINES)": "semi-essential",
    "AEORFLOT": "semi-essential",
    "QUANTAS": "semi-essential",
    "ALITALIA": "semi-essential",
    "SAUDIA ARABIAN AIRLINES": "semi-essential",
    "SWISSAIR": "semi-essential",
    "SAS": "semi-essential",
    "SOUTH AFRICAN AIRWAYS": "semi-essential",
    "VARIG (BRAZIL)": "semi-essential",
    "AIR-INDIA": "semi-essential",
    "AIR ALGERIE": "semi-essential",
    "PHILIPPINE AIRLINES": "semi-essential",
    "MEXICANA": "semi-essential",
    "PAKISTAN INTERNATIONAL": "semi-essential",
    "AIR NEW ZEALAND": "semi-essential",
    "UTA/INTERAIR": "semi-essential",
    "AIR MALTA": "semi-essential",
    "SABENA": "semi-essential",
    "AEROLINEAS ARGENTINAS": "semi-essential",
    "OLYMPIC AIRWAYS": "semi-essential",
    "EL AL": "semi-essential",
    "ANSETT AIRLINES": "semi-essential",
    "AUSTRAINLIAN AIRLINES": "semi-essential",
    "TAP (PORTUGAL)": "semi-essential",
    "VASP (BRAZIL)": "semi-essential",
    "EGYPTAIR": "semi-essential",
    "KUWAIT AIRLINES": "semi-essential",
    "AVIANCA": "semi-essential",
    "GULF AIR (BAHRAIN)": "semi-essential",
    "BALKAN-BULGARIAN AIRLINES": "semi-essential",
    "FINNAIR": "semi-essential",
    "AER LINGUS": "semi-essential",
    "AIR LANKA": "semi-essential",
    "NIGERIA AIRWAYS": "semi-essential",
    "CRUZEIRO DO SUL (BRAZIJ)": "semi-essential",
    "THY (TURKEY)": "semi-essential",
    "ROYAL AIR MAROC": "semi-essential",
    "TUNIS AIR": "semi-essential",
    "ICELANDAIR": "semi-essential",
    "AUSTRIAN AIRLINES": "semi-essential",
    "LANCHILE": "semi-essential",
    "AVIACO (SPAIN)": "semi-essential",
    "LADECO (CHILE)": "semi-essential",
    "LAB (BOLIVIA)": "semi-essential",
    "QUEBECAIRE": "semi-essential",
    "EASTWEST AIRLINES (AUSTRALIA)": "semi-essential",
    "DELTA": "semi-essential",
    "NORTHWEST": "semi-essential",
    "CONTINENTAL": "semi-essential",
    "WESTERN": "semi-essential",
    "US AIR": "semi-essential",
    "AIRINTER": "semi-essential",
    "SOUTHWEST": "semi-essential",
    "AIR BRITISH COLUBIA": "semi-essential",
    "SINGAPORE AIRLINES": "semi-essential",
    "AEROMEXICO": "semi-essential",
    "THAI AIRWAYS": "semi-essential",
    "CHINA AIRLINES": "semi-essential",
    "NORDAIR": "semi-essential",
    "KOREAN AIRLINES": "semi-essential",
    "AIR AFRIGUE": "semi-essential",
    "EVA AIRLINES": "semi-essential",
    "MIDWEST EXPRESS AIRLINES, INC.": "semi-essential",
    "METRO AIRLINES": "semi-essential",
    "CROATIA AIRLINES": "semi-essential",
    "TRANSAERO": "semi-essential",
    "ZAMBIA AIRWAYS": "semi-essential",
    "AIR ZIMBABWE": "semi-essential",
    "CATHAY PACIFIC": "semi-essential",
    "MALAYSIAN AIRLINE SYSTEM": "semi-essential",
    "IBERIA": "semi-essential",
    "GARUDA (INDONESIA)": "semi-essential",
    "BRAATHENS S.A.F.E. (NORWAY)": "semi-essential",
    "WINGS AIRWAYS": "semi-essential",
    "BRITISH MIDLAND": "semi-essential",
    "WINDWARD ISLAND": "semi-essential",
    "VIASA": "semi-essential",
    "VALLEY AIRLINES": "semi-essential",
    "TAN": "semi-essential",
    "TALAIR": "semi-essential",
    "TACA INTERNATIONAL": "semi-essential",
    "SURINAM AIRWAYS": "semi-essential",
    "SUN WORLD INTERNATIONAL": "semi-essential",
    "SUNBELT AIRLINES": "semi-essential",
    "SUDAN AIRWAYS": "semi-essential",
    "SINGLETON": "semi-essential",
    "SIMMONS AIRLINES": "semi-essential",
    "SCENIC AIRLINES": "semi-essential",
    "VIRGIN ATLANTIC": "semi-essential",
    "SAN JUAN AIRLINES": "semi-essential",
    "LUXAIR": "semi-essential",
    "AIR ZAIRE": "semi-essential",
    "PRINCEVILLE": "semi-essential",
    "PBA": "semi-essential",
    "ALL NIPPON AIRWAYS": "semi-essential",
    "NORONTAIR": "semi-essential",
    "NEW YORK HELICOPTER": "semi-essential",
    "NOUNT COOK": "semi-essential",
    "CANADIAN AIRLINES INTERNATIONAL": "semi-essential",
    "NATIONAIR": "semi-essential",
    "METROFLIGHT AIRLINES": "semi-essential",
    "MESA AIR": "semi-essential",
    "MALEV": "semi-essential",
    "LOT (POLAND)": "semi-essential",
    "LIAT": "semi-essential",
    "LAV (VENEZUELA)": "semi-essential",
    "LAP (PARAGUAY)": "semi-essential",
    "LACSA (COSTA RICA)": "semi-essential",
    "JUGOSLAV AIR": "semi-essential",
    "ISLAND AIRLINES": "semi-essential",
    "IRAN AIR": "semi-essential",
    "INDIAN AIRLINES": "semi-essential",
    "HAWAIIAN AIR": "semi-essential",
    "HAVASU AIRLINES": "semi-essential",
    "FUYANA AIRWAYS": "semi-essential",
    "GOLDEN PACIFIC AIR": "semi-essential",
    "FREEDOM AIR": "semi-essential",
    "DOMINICANA": "semi-essential",
    "DAN AIR SERVICES": "semi-essential",
    "CUMBERLAND AIRLINES": "semi-essential",
    "CSA": "semi-essential",
    "CROWN AIR": "semi-essential",
    "COPA": "semi-essential",
    "COMPANIA FAUCETT": "semi-essential",
    "TRANSPORTES AEROS MILITARES ECCUATORANOS": "semi-essential",
    "COMMAND AIRWAYS": "semi-essential",
    "COMAIR": "semi-essential",
    "CAYMAN AIRWAYS": "semi-essential",
    "SAETA SOCIAEDAD ECUATORIANOS DE TRANSPORTES AEREOS": "semi-essential",
    "SASHA SERVICIO AERO DE HONDURAS": "semi-essential",
    "CAPITOL AIR": "semi-essential",
    "BWIA": "semi-essential",
    "BROKWAY AIR": "semi-essential",
    "BEMIDJI AIRLINES": "semi-essential",
    "BAR HARBOR AIRLINES": "semi-essential",
    "BAHAMASAIR": "semi-essential",
    "AVIATECA (GUATEMALA)": "semi-essential",
    "AVENSA": "semi-essential",
    "AUSTRIAN AIR SERVICE": "semi-essential",
    "ALOHA AIRLINES": "semi-essential",
    "ALM": "semi-essential",
    "AMERICA WEST": "semi-essential",
    "TRUMP AIRLINE": "semi-essential",
    "ALASKA AIRLINES": "semi-essential",
    "AMERICAN TRANS AIR": "semi-essential",
    "AIR CHINA": "semi-essential",
    "RENO AIR, INC.": "semi-essential",
    "AIR SEYCHELLES": "semi-essential",
    "AIR PANAMA": "semi-essential",
    "AIR JAMAICA": "semi-essential",
    "AIR DJIBOUTI": "semi-essential",
    "AERO VIRGIN ISLANDS": "semi-essential",
    "AERO PERU": "semi-essential",
    "AEROLINEAS NICARAGUENSIS": "semi-essential",
    "AERO COACH AVAIATION": "semi-essential",
    "ARIANA AFGHAN": "semi-essential",
    "CYPRUS AIRWAYS": "semi-essential",
    "ECUATORIANA": "semi-essential",
    "ETHIOPIAN AIRLINES": "semi-essential",
    "KENYA AIRLINES": "semi-essential",
    "AIR MAURITIUS": "semi-essential",
    "WIDERO'S FLYVESELSKAP": "semi-essential",
    "AFFILIATED AUTO RENTAL": "semi-essential",
    "AMERICAN INTL RENT-A-CAR": "semi-essential",
    "BROOKS RENT-A-CAR": "semi-essential",
    "ACTION AUTO RENTAL": "semi-essential",
    "HERTZ RENT-A-CAR": "semi-essential",
    "PAYLESS CAR RENTAL": "semi-essential",
    "SNAPPY CAR RENTAL": "semi-essential",
    "AIRWAYS RENT-A-CAR": "semi-essential",
    "ALTRA AUTO RENTAL": "semi-essential",
    "AGENCY RENT-A-CAR": "semi-essential",
    "BUDGET RENT-A-CAR": "semi-essential",
    "HOLIDAY RENT-A-WRECK": "semi-essential",
    "RENT-A-WRECK": "semi-essential",
    "AJAX RENT-A-CAR": "semi-essential",
    "EUROP CAR": "semi-essential",
    "TROPICAL RENT-A-CAR": "semi-essential",
    "SHOWCASE RENTAL CARS": "semi-essential",
    "ALAMO RENT-A-CAR": "semi-essential",
    "AVIS RENT-A-CAR": "semi-essential",
    "DOLLAR RENT-A-CAR": "semi-essential",
    "EUROPE BY CAR": "semi-essential",
    "NATIONAL CAR RENTAL": "semi-essential",
    "KEMWELL GROUP RENT-A-CAR": "semi-essential",
    "THRIFTY RENT-A-CAR": "semi-essential",
    "TILDEN TENT-A-CAR": "semi-essential",
    "ECONO-CAR RENT-A-CAR": "semi-essential",
    "AUTO HOST COST CAR RENTALS": "semi-essential",
    "ENTERPRISE RENT-A-CAR": "semi-essential",
    "GENERAL RENT-A-CAR": "semi-essential",
    "A-1 RENT-A-CAR": "semi-essential",
    "GODFREY NATL RENT-A-CAR": "semi-essential",
    "ALPHA RENT-A-CAR": "semi-essential",
    "ANSA INTL RENT-A-CAR": "semi-essential",
    "ALLSTAE RENT-A-CAR": "semi-essential",
    "AVCAR RENT-A-CAR": "semi-essential",
    "AUTOMATE RENT-A-CAR": "semi-essential",
    "AVON RENT-A-CAR": "semi-essential",
    "CAREY RENT-A-CAR": "semi-essential",
    "INSURANCE RENT-A-CAR": "semi-essential",
    "MAJOR RENT-A-CAR": "semi-essential",
    "REPLACEMENT RENT-A-CAR": "semi-essential",
    "RESERVE RENT-A-CAR": "semi-essential",
    "UGLY DUCKLING RENT-A-CAR": "semi-essential",
    "USA RENT-A-CAR": "semi-essential",
    "VALUE RENT-A-CAR": "semi-essential",
    "AUTOHANSA RENT-A-CAR": "semi-essential",
    "CITE RENT-A-CAR": "semi-essential",
    "INTERENT RENT-A-CAR": "semi-essential",
    "MILLEVILLE RENT-A-CAR": "semi-essential",
    "VIA ROUTE RENT-A-CAR": "semi-essential",
    "HOLIDAY INN EXPRESS": "semi-essential",
    "HOLIDAY INNS": "semi-essential",
    "BEST WESTERN HOTELS": "semi-essential",
    "SHERATON HOTELS": "semi-essential",
    "HILTON HOTELS": "semi-essential",
    "FORTE HOTELS": "semi-essential",
    "GOLDEN TULIP HOTELS": "semi-essential",
    "FRIENDSHIP INNS": "semi-essential",
    "QUALITY INNS": "semi-essential",
    "QUALITY SUITES": "semi-essential",
    "MARRIOTT HOTELS": "semi-essential",
    "DAYS INN": "semi-essential",
    "DAYSTOP": "semi-essential",
    "ARABELLA HOTELS": "semi-essential",
    "INTER-CONTINENTAL HOTELS": "semi-essential",
    "WESTIN HOTELS": "semi-essential",
    "RODEWAY INNS": "semi-essential",
    "LA QUINTA MOTOR INNS": "semi-essential",
    "AMERICANA HOTELS": "semi-essential",
    "SOL HOTELS": "semi-essential",
    "PULLMAN INTERNATIONAL HOTELS": "semi-essential",
    "MERIDIEN HOTELS": "semi-essential",
    "CREST HOTELS (see FORTE HOTELS)": "semi-essential",
    "TOKYO HOTEL": "semi-essential",
    "PENNSULA HOTEL": "semi-essential",
    "WELCOMGROUP HOTELS": "semi-essential",
    "DUNFEY HOTELS": "semi-essential",
    "PRINCE HOTELS": "semi-essential",
    "DOWNTOWNER-PASSPORT HOTEL": "semi-essential",
    "RED LION HOTELS": "semi-essential",
    "RED LION INNS": "semi-essential",
    "CP HOTELS": "semi-essential",
    "RENAISSANCE HOTELS": "semi-essential",
    "STOUFFER HOTELS": "semi-essential",
    "ASTIR HOTELS": "semi-essential",
    "SUN ROUTE HOTELS": "semi-essential",
    "HOTEL IBIS": "semi-essential",
    "SOUTHERN PACIFIC HOTELS": "semi-essential",
    "HILTON INTERNATIONAL": "semi-essential",
    "AMFAC HOTELS": "semi-essential",
    "ANA HOTEL": "semi-essential",
    "CONCORDE HOTELS": "semi-essential",
    "IBEROTEL HOTELS": "semi-essential",
    "HOTEL OKURA": "semi-essential",
    "ROYAL HOTELS": "semi-essential",
    "FOUR SEASONS HOTELS": "semi-essential",
    "CIGA HOTELS": "semi-essential",
    "SHANGRI-LA INTERNATIONAL": "semi-essential",
    "HOTELES MELIA": "semi-essential",
    "AUBERGE DES GOVERNEURS": "semi-essential",
    "REGAL 8 INNS": "semi-essential",
    "COAST HOTELS": "semi-essential",
    "PARK INNS INTERNATIONAL": "semi-essential",
    "JOLLY HOTELS": "semi-essential",
    "COMFORT INNS": "semi-essential",
    "JOURNEY'S END MOTLS": "semi-essential",
    "RELAX INNS": "semi-essential",
    "LADBROKE HOTELS": "semi-essential",
    "FORUM HOTELS": "semi-essential",
    "PANNONIA HOTELS": "semi-essential",
    "MIYAKO HOTELS": "semi-essential",
    "SANDMAN HOTELS": "semi-essential",
    "VENTURE INNS": "semi-essential",
    "VAGABOND HOTELS": "semi-essential",
    "MANDARIN ORIENTAL HOTEL": "semi-essential",
    "HOTEL MERCURE": "semi-essential",
    "DELTA HOTEL": "semi-essential",
    "SAS HOTELS": "semi-essential",
    "PRINCESS HOTELS INTERNATIONAL": "semi-essential",
    "HUNGAR HOTELS": "semi-essential",
    "SOKOS HOTELS": "semi-essential",
    "DORAL HOTELS": "semi-essential",
    "HELMSLEY HOTELS": "semi-essential",
    "FAIRMONT HOTELS": "semi-essential",
    "SONESTA HOTELS": "semi-essential",
    "OMNI HOTELS": "semi-essential",
    "CUNARD HOTELS": "semi-essential",
    "HOSPITALITY INTERNATIONAL": "semi-essential",
    "REGENT INTERNATIONAL HOTELS": "semi-essential",
    "ΡΑΝΝΟΝΙA HOTELS": "semi-essential",
    "NOAH'S HOTELS": "semi-essential",
    "MOVENPICK HOTELS": "semi-essential",
    "TRAVELODGE": "semi-essential",
    "TELFORD INTERNATIONAL": "semi-essential",
    "MERLIN HOTELS": "semi-essential",
    "DORINT HOTELS": "semi-essential",
    "HOTLE UNIVERSALE": "semi-essential",
    "DAN HOTELS": "semi-essential",
    "RANK HOTELS": "semi-essential",
    "SWISSOTEL": "semi-essential",
    "RESO HOTELS": "semi-essential",
    "SAROVA HOTELS": "semi-essential",
    "RAMADA INNS": "semi-essential",
    "RAMADA LIMITED": "semi-essential",
    "HO JO INN": "semi-essential",
    "HOWARD JOHNSON": "semi-essential",
    "MOUNT CHARLOTTE THISTLE": "semi-essential",
    "HYATT HOTEL": "semi-essential",
    "SOFITEL HOTELS": "semi-essential",
    "NOVOTEL HOTELS": "semi-essential",
    "STEIGENBERGER HOTELS": "semi-essential",
    "ECONO LODGES": "semi-essential",
    "QUEENS MOAT HOUSES": "semi-essential",
    "SWALLOW HOTELS": "semi-essential",
    "HUSA HOTELS": "semi-essential",
    "DE VERE HOTELS": "semi-essential",
    "RADISSON HOTELS": "semi-essential",
    "RED ROOK INNS": "semi-essential",
    "IMPERIAL LONDON HOTEL": "semi-essential",
    "EMBASSY HOTELS": "semi-essential",
    "PENTA HOTELS": "semi-essential",
    "LOEWS HOTELS": "semi-essential",
    "SCANDIC HOTELS": "semi-essential",
    "SARA HOTELS": "semi-essential",
    "OBEROI HOTELS": "semi-essential",
    "OTANI HOTELS": "semi-essential",
    "TAJ HOTELS INTERNATIONAL": "semi-essential",
    "KNIGHTS INNS": "semi-essential",
    "METROPOLE HOTELS": "semi-essential",
    "HOTELES EL PRESIDENTS": "semi-essential",
    "FLAG INN": "semi-essential",
    "HAMPTON INNS": "semi-essential",
    "STAKIS HOTELS": "semi-essential",
    "MARITIM HOTELS": "semi-essential",
    "ARCARD HOTELS": "semi-essential",
    "ARCTIA HOTELS": "semi-essential",
    "CAMPANIEL HOTELS": "semi-essential",
    "IBUSZ HOTELS": "semi-essential",
    "RANTASIPI HOTELS": "semi-essential",
    "INTERHOTEL CEDOK": "semi-essential",
    "CLIMAT DE FRANCE HOTELS": "semi-essential",
    "CUMULUS HOTELS": "semi-essential",
    "DANUBIUS HOTEL": "semi-essential",
    "ADAMS MARK HOTELS": "semi-essential",
    "ALLSTAR INNS": "semi-essential",
    "BUDGET HOST INNS": "semi-essential",
    "BUDGETEL HOTELS": "semi-essential",
    "SUISSE CHALETS": "semi-essential",
    "CLARION HOTELS": "semi-essential",
    "COMPRI HOTELS": "semi-essential",
    "COURTYARD BY MARRIOTT": "semi-essential",
    "CONSORT HOTELS": "semi-essential",
    "DILLION INNS": "semi-essential",
    "DOUBLETREE HOTELS": "semi-essential",
    "DRURY INNS": "semi-essential",
    "ECONOMY INNS OF AMERICA": "semi-essential",
    "EMBASSY SUITES": "semi-essential",
    "EXEL INNS": "semi-essential",
    "FARFIELD HOTELS": "semi-essential",
    "HARLEY HOTELS": "semi-essential",
    "MIDWAY MOTOR LODGE": "semi-essential",
    "MOTEL 6": "semi-essential",
    "GUEST QUARTERS (Formally PICKETT SUITE HOTELS)": "semi-essential",
    "THE REGISTRY HOTELS": "semi-essential",
    "RESIDENCE INNS": "semi-essential",
    "ROYCE HOTELS": "semi-essential",
    "SANDMAN INNS": "semi-essential",
    "SHILO INNS": "semi-essential",
    "SHONEY'S INNS": "semi-essential",
    "SUPER8 MOTELS": "semi-essential",
    "THE RITZ CARLTON HOTELS": "semi-essential",
    "FLAG INNS (AUSRALIA)": "semi-essential",
    "GOLDEN CHAIN HOTEL": "semi-essential",
    "QUALITY PACIFIC HOTEL": "semi-essential",
    "FOUR SEASONS HOTEL (AUSTRALIA)": "semi-essential",
    "FARIFIELD INN": "semi-essential",
    "CARLTON HOTELS": "semi-essential",
    "CITY LODGE HOTELS": "semi-essential",
    "KAROS HOTELS": "semi-essential",
    "PROTEA HOTELS": "semi-essential",
    "SOUTHERN SUN HOTELS": "semi-essential",
    "HILTON CONRAD": "semi-essential",
    "WYNDHAM HOTEL AND RESORTS": "semi-essential",
    "RICA HOTELS": "semi-essential",
    "INER NOR HOTELS": "semi-essential",
    "SEAINES PLANATION": "semi-essential",
    "RIO SUITES": "semi-essential",
    "BROADMOOR HOTEL": "semi-essential",
    "BALLY'S HOTEL AND CASINO": "discretionary",
    "JOHN ASCUAGA'S NUGGET": "discretionary",
    "MGM GRAND HOTEL": "semi-essential",
    "HARRAH'S HOTELS AND CASINOS": "discretionary",
    "OPRYLAND HOTEL": "semi-essential",
    "BOCA RATON RESORT": "semi-essential",
    "HARVEY/BRISTOL HOTELS": "semi-essential",
    "MASTERS ECONOMY INNS": "semi-essential",
    "COLORADO BELLE/EDGEWATER RESORT": "semi-essential",
    "RIVIERA HOTEL AND CASINO": "discretionary",
    "TROPICANA RESORT AND CASINO": "discretionary",
    "WOODSIDE HOTELS AND RESORTS": "semi-essential",
    "TOWNPLACE SUITES": "semi-essential",
    "MILLENIUM BROADWAY HOTEL": "semi-essential",
    "CLUB MED": "discretionary",
    "BILTMORE HOTEL AND SUITES": "semi-essential",
    "CAREFREE RESORTS": "semi-essential",
    "ST. REGIS HOTEL": "semi-essential",
    "THE ELIOT HOTEL": "semi-essential",
    "CLUBCORP/CLUB RESORTS": "discretionary",
    "WELESLEY INNS": "semi-essential",
    "THE BEVERLY HILLS HOTEL": "semi-essential",
    "CROWNE PLAZA HOTELS": "semi-essential",
    "HOMEWOOD SUITES": "semi-essential",
    "PEABODY HOTELS": "semi-essential",
    "GREENBRIAH RESORTS": "semi-essential",
    "AMELIA ISLAND PLANATION": "semi-essential",
    "THE HOMESTEAD": "semi-essential",
    "SOUTH SEAS RESORTS": "semi-essential",
    "Local/Suburban Commuter Passenger Transportation – Railroads, Feries, Local Water Transportation.": "essential",
    "Passenger Railways": "essential",
    "Ambulance Services": "essential",
    "Taxicabs and Limousines": "semi-essential",
    "Bus Lines, Including Charters, Tour Buses": "semi-essential",
    "Tour Buses": "discretionary",
    "Delivery Services – Local": "semi-essential",
    "Freight Carriers": "essential",
    "Motor Freight Carriers": "essential",
    "Moving and Storage Companies": "semi-essential",
    "Trucking - Local/Long Distance": "semi-essential",
    "Courier Services - Air or Ground": "semi-essential",
    "Fright Forwarders": "semi-essential",
    "Storage": "semi-essential",
    "Warehousing, Public": "semi-essential",
    "Cruise Lines": "discretionary",
    "Steamship Lines": "semi-essential",
    "Boat Rentals and Leases": "discretionary",
    "Marinas, Marine Service, and Supplies": "semi-essential",
    "Airlines, Air Carriers (not listed elsewhere)": "semi-essential",
    "Airports, Airport Terminals": "essential",
    "Flying Fields": "discretionary",
    "Travel Agencies and Tour Operations": "discretionary",
    "Package Tour Operators (For use in Germany only)": "discretionary",
    "Toll and Bridge Fees": "essential",
    "Transportation Services, Not elsewhere classified)": "essential",
    "Telecommunications Equipment including telephone sales": "semi-essential",
    "Fax services": "semi-essential",
    "Telecommunication service including local and long distance calls, credit card calls, calls through use of magnetic-strip reading telephones and fax services": "essential",
    "VisaPhone": "semi-essential",
    "Telegraph services": "semi-essential",
    "Money Orders – Wire Transfer": "semi-essential",
    "Cable and other pay television (previously Cable Services)": "semi-essential",
    "Electric, Gas, Sanitary and Water Utilities": "essential",
    "Motor vehicle supplies and new parts": "semi-essential",
    "Office and Commercial Furniture": "semi-essential",
    "Construction Materials, Not Elsewhere Classified": "semi-essential",
    "Office, Photographic, Photocopy, and Microfilm Equipment": "semi-essential",
    "Computers, Computer Peripheral Equipment, Software": "semi-essential",
    "Commercial Equipment, Not Elsewhere Classified": "semi-essential",
    "Medical, Dental Ophthalmic, Hospital Equipment and Supplies": "essential",
    "Metal Service Centers and Offices": "semi-essential",
    "Electrical Parts and Equipment": "semi-essential",
    "Hardware Equipment and Supplies": "semi-essential",
    "Plumbing and Heating Equipment and Supplies": "semi-essential",
    "Industrial Supplies, Not Elsewhere Classified": "semi-essential",
    "Precious Stones and Metals, Watches and Jewelry": "discretionary",
    "Durable Goods, Not Elsewhere Classified": "semi-essential",
    "Stationery, Office Supplies, Printing, and Writing Paper": "semi-essential",
    "Drugs, Drug Proprietors, and Druggist's Sundries": "essential",
    "Piece Goods, Notions, and Other Dry Goods": "semi-essential",
    "Men's Women's and Children's Uniforms and Commercial Clothing": "semi-essential",
    "Commercial Footwear": "semi-essential",
    "Chemicals and Allied Products, Not Elsewhere Classified": "semi-essential",
    "Petroleum and Petroleum Products": "essential",
    "Books, Periodicals, and Newspapers": "semi-essential",
    "Florists' Supplies, Nursery Stock and Flowers": "semi-essential",
    "Paints, Varnishes, and Supplies": "semi-essential",
    "Non-durable Goods, Not Elsewhere Classified": "semi-essential",
    "Home Supply Warehouse Stores": "semi-essential",
    "Lumber and Building Materials Stores": "semi-essential",
    "Glass Stores": "semi-essential",
    "Paint and Wallpaper Stores": "semi-essential",
    "Wallpaper Stores": "semi-essential",
    "Hardware Stores": "semi-essential",
    "Nurseries – Lawn and Garden Supply Store": "semi-essential",
    "Mobile Home Dealers": "semi-essential",
    "Wholesale Clubs": "semi-essential",
    "Duty Free Store": "discretionary",
    "Discount Stores": "semi-essential",
    "Department Stores": "semi-essential",
    "Variety Stores": "semi-essential",
    "Misc. General Merchandise": "semi-essential",
    "Grocery Stores": "essential",
    "Supermarkets": "essential",
    "Freezer and Locker Meat Provisioners": "essential",
    "Meat Provisioners - Freezer and Locker": "essential",
    "Candy Stores": "discretionary",
    "Confectionery Stores": "discretionary",
    "Nut Stores": "discretionary",
    "Dairy Products Stores": "essential",
    "Bakeries": "semi-essential",
    "Misc. Food Stores – Convenience Stores and Specialty Markets": "essential",
    "Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing": "semi-essential",
    "Automobile and Truck Dealers (Used Only)": "semi-essential",
    "Automobile Supply Stores": "semi-essential",
    "Automotive Tire Stores": "semi-essential",
    "Automotive Parts, Accessories Stores": "semi-essential",
    "Service Stations (with or without ancillary services)": "essential",
    "Automated Fuel Dispensers": "essential",
    "Boat Dealers": "discretionary",
    "Recreational and Utility Trailers, Camp Dealers": "discretionary",
    "Motorcycle Dealers": "semi-essential",
    "Motor Home Dealers": "discretionary",
    "Snowmobile Dealers": "discretionary",
    "Barber and Beauty Shops": "discretionary",
    "Men's and Boy's Clothing and Accessories Stores": "semi-essential",
    "Women's Ready-to-Wear Stores": "semi-essential",
    "Women's Accessory and Specialty Shops": "semi-essential",
    "Children's and Infant's Wear Stores": "semi-essential",
    "Family Clothing Stores": "semi-essential",
    "Sports Apparel, Riding Apparel Stores": "discretionary",
    "Shoe Stores": "semi-essential",
    "Furriers and Fur Shops": "discretionary",
    "Men's and Women's Clothing Stores": "semi-essential",
    "Tailors, Seamstress, Mending, and Alterations": "semi-essential",
    "Wig and Toupee Stores": "discretionary",
    "Miscellaneous Apparel and Accessory Shops": "discretionary",
    "Furniture, Home Furnishings, and Equipment Stores, Except Appliances": "semi-essential",
    "Floor Covering Stores": "semi-essential",
    "Drapery, Window Covering and Upholstery Stores": "semi-essential",
    "Fireplace, Fireplace Screens, and Accessories Stores": "semi-essential",
    "Miscellaneous Home Furnishing Specialty Stores": "semi-essential",
    "Household Appliance Stores": "semi-essential",
    "Electronic Sales": "semi-essential",
    "Music Stores, Musical Instruments, Piano Sheet Music": "discretionary",
    "Computer Software Stores": "semi-essential",
    "Record Shops": "discretionary",
    "Caterers": "semi-essential",
    "Eating places and Restaurants": "semi-essential",
    "Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail lounges, Nightclubs and Discotheques": "discretionary",
    "Fast Food Restaurants": "semi-essential",
    "Misc. Food Stores & Convenience Stores and Specialty Markets": "semi-essential",
    "Drug Stores and Pharmacies": "essential",
    "Car Washes": "semi-essential",
    "Tire Re-treading and Repair Shops": "essential",
    "Video Tape Rental Stores": "discretionary",
    "Cosmetic Stores": "discretionary",
    "Radio Repair Shops": "semi-essential",
    "Massage Parlors": "discretionary",
    "Automotive Body Repair Shops": "semi-essential",
    "Vocational Schools and Trade Schools": "semi-essential",
    "Local/Suburban Commuter Passenger Transportation": "essential",
    "Courier Services – Air or Ground": "semi-essential",
    "Colleges, Junior Colleges, Universities": "semi-essential",
    "Elementary and Secondary Schools": "essential",
    "Security Brokers/Dealers": "semi-essential",
    "Paint Shops – Automotive": "semi-essential",
    "Meat Provisioners – Freezer and Locker": "essential",
    "Financial Institutions – Merchandise and Services": "essential",
    "Automobile Parking Lots and Garages": "semi-essential",
    "Tax Preparation Service": "semi-essential",
    "Health and Beauty Shops": "semi-essential",
    "Insurance Sales, Underwriting, and Premiums": "semi-essential",
    "Child Care Services": "essential",
    "Towing Services": "essential",
    "Automotive Service Shops": "semi-essential",
    "Service Stations": "essential",
    "Financial Institutions – Manual Cash Disbursements": "essential"

}

# Function to return the service essence of a merchant
def categorize_merchant(merchant):
    if merchant in merchant_spending_type:
        return merchant_spending_type[merchant]
    else:
        print("Merchant category not mapped to essence: ", merchant)

    return 'semi-essential'
